name: chatapp
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.3.2
  file_picker: ^6.1.1
  image_picker: ^1.0.0
  country_picker: ^2.0.20
  permission_handler: ^11.1.0
  shared_preferences: ^2.0.20
  intl: ^0.19.0
  emoji_picker_flutter: ^1.5.2
  flutter_keyboard_visibility: ^6.0.0
  phone_number: ^2.0.1
  uuid: ^3.0.7
  share_plus: ^7.0.2
  url_launcher: ^6.1.10
  flutter_contacts: ^1.1.6
  cached_network_image: ^3.2.3
  path_provider: ^2.0.15
  firebase_storage: ^11.2.4
  flutter_emoji: ^2.4.0
  video_player: ^2.7.0
  mime: ^1.0.4
  open_file_plus: ^3.4.1
  logger: ^1.1.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  firebase_messaging: ^14.6.5
  http: ^1.1.0
  visibility_detector: ^0.4.0+2
  image: ^4.0.17
  audioplayers: ^5.1.0
  flutter_sound: ^9.2.13
  audio_session: ^0.1.16
  camera: ^0.10.5+3
  photo_manager: ^3.0.0-dev.2
  google_fonts: ^6.1.0
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.suyati.project
        pluginClass: ProjectPlugin
      ios:
        pluginClass: ProjectPlugin
      linux:
        pluginClass: ProjectPlugin
      macos:
        pluginClass: ProjectPlugin
      windows:
        pluginClass: ProjectPluginCApi
      web:
        pluginClass: ProjectWeb
        fileName: project_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

  assets:
    - assets/images/landing_img.png
    - assets/images/PENDING.png
    - assets/images/SENT.png
    - assets/images/DELIVERED.png
    - assets/images/SEEN.png
    - assets/images/dark/chat_bg.png
    - assets/images/chat_bg.png
    - assets/images/logo.png
    - assets/images/avatar.png

  fonts:
    - family: AzeretMono
      fonts:
        - asset: assets/fonts/AzeretMono-Regular.ttf