// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB0grs8GHbcrDwohLaHAHMz7ia0aZ9GcA',
    appId: '1:34700240102:web:a9fce5596b702c1ed7c727',
    messagingSenderId: '34700240102',
    projectId: 'testsociallogin-2a372',
    authDomain: 'testsociallogin-2a372.firebaseapp.com',
    storageBucket: 'testsociallogin-2a372.appspot.com',
    measurementId: 'G-ZR89F7HF9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd7jYwJ0yeztcE0sRGOvNXnLBuqw7-N1I',
    appId: '1:34700240102:android:55ade8a25f225f59d7c727',
    messagingSenderId: '34700240102',
    projectId: 'testsociallogin-2a372',
    storageBucket: 'testsociallogin-2a372.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdTndiUJvodqy5MGRRHPKx7eq6hkKYNP4',
    appId: '1:34700240102:ios:a4dbeee09020a61dd7c727',
    messagingSenderId: '34700240102',
    projectId: 'testsociallogin-2a372',
    storageBucket: 'testsociallogin-2a372.appspot.com',
    androidClientId: '34700240102-pe0qn74qap285blauvbeqhrlgffb0ll7.apps.googleusercontent.com',
    iosClientId: '34700240102-8hp4qjnuc10anhqpkrrbc2p5g536b0me.apps.googleusercontent.com',
    iosBundleId: 'com.suyati.TestDemo.testdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdTndiUJvodqy5MGRRHPKx7eq6hkKYNP4',
    appId: '1:34700240102:ios:a4dbeee09020a61dd7c727',
    messagingSenderId: '34700240102',
    projectId: 'testsociallogin-2a372',
    storageBucket: 'testsociallogin-2a372.appspot.com',
    androidClientId: '34700240102-pe0qn74qap285blauvbeqhrlgffb0ll7.apps.googleusercontent.com',
    iosClientId: '34700240102-8hp4qjnuc10anhqpkrrbc2p5g536b0me.apps.googleusercontent.com',
    iosBundleId: 'com.suyati.TestDemo.testdemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB0grs8GHbcrDwohLaHAHMz7ia0aZ9GcA',
    appId: '1:34700240102:web:7f6f5f6bb5f21dc6d7c727',
    messagingSenderId: '34700240102',
    projectId: 'testsociallogin-2a372',
    authDomain: 'testsociallogin-2a372.firebaseapp.com',
    storageBucket: 'testsociallogin-2a372.appspot.com',
    measurementId: 'G-RLSZ9MMW75',
  );
}
